### ISSUE TITLE
Bounds error panic in `Buffer::set_stringn` with trailing 0-width unicode graphemes

### ISSUE THREAD

**Issue by jonaskoelker** [fdehau/tui-rs#282]
The following program panics:
```
use tui::{buffer::Buffer, layout::Rect, style::Style};

fn main() {
    let bug_exhibitor = " \u{1}"; // grapheme widths: 1 (' ') and 0 ('^A')
    let area = Rect { x: 0, y: 0, width: 1, height: 1 };
    let mut buffer = Buffer::empty(area);
    buffer.set_stringn(0, 0, bug_exhibitor, 1, Style::default());
}
```

In particular:
```zsh% RUST_BACKTRACE=full cargo run --bin sandbox
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/sandbox`
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2797:14
stack backtrace:
   0:     0x560719206c64 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x560719206c64 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x560719206c64 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x560719206c64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56071921d52c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x560719205527 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x560719208cc5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x560719208cc5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x560719208cc5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x5607192089b1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x56071920927a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x560719208e60 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x56071921c9f1 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x56071921c9b5 - core::panicking::panic_bounds_check::h09b793daa6d169ff
                               at src/libcore/panicking.rs:63
  14:     0x5607191f42c7 - <usize as core::slice::SliceIndex<[T]>>::index_mut::hcf11f5fa550ff5a9
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2797
  15:     0x5607191f06f8 - core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::h7fa2dcbf0345bc9c
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2667
  16:     0x5607191f3dfb - <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut::h26fb87fbf9019658
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1895
  17:     0x5607191f1293 - tui::buffer::Buffer::set_stringn::h505c8996e2f56ac5
                               at /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/buffer.rs:331
  18:     0x5607191f054e - sandbox::main::h0540c5fa116adc70
                               at src/sandbox.rs:7
  19:     0x5607191f0480 - std::rt::lang_start::{{closure}}::hce1bd3b6693bbb74
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  20:     0x560719208d93 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  21:     0x560719208d93 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  22:     0x56071920a4f7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  23:     0x560719209720 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  24:     0x560719209720 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  25:     0x560719209720 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  26:     0x5607191f0459 - std::rt::lang_start::h85b998b54eced48f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  27:     0x5607191f05aa - main
  28:     0x7ff18be0fb97 - __libc_start_main
  29:     0x5607191f023a - _start
  30:                0x0 - <unknown>
```

I expect this program to not panic. In particular, I expect `buffer` to contain a single `Cell` with the space character in the default style. More generally, if the string starts with zero or more 0-width graphemes followed by a 1-width grapheme followed by whatever, I expect the single `Cell` to contain the first width-1 grapheme, otherwise I expect it to contain the default character (space).

The exact `set_stringn` I found in `~/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.9.1/src/buffer.rs` looks like this:

```
    /// Print at most the first n characters of a string if enough space is available
    /// until the end of the line
    pub fn set_stringn<S>(
        &mut self,
        x: u16,
        y: u16,
        string: S,
        width: usize,
        style: Style,
    ) -> (u16, u16)
    where
        S: AsRef<str>,
    {
        let mut index = self.index_of(x, y);
        let mut x_offset = x as usize;
        let graphemes = UnicodeSegmentation::graphemes(string.as_ref(), true);
        let max_offset = min(self.area.right() as usize, width.saturating_add(x as usize));
        for s in graphemes {
            let width = s.width();
            // `x_offset + width > max_offset` could be integer overflow on 32-bit machines if we
            // change dimenstions to usize or u32 and someone resizes the terminal to 1x2^32.
            if width > max_offset.saturating_sub(x_offset) {
                break;
            }

            self.content[index].set_symbol(s);
            self.content[index].set_style(style);
            // Reset following cells if multi-width (they would be hidden by the grapheme),
            for i in index + 1..index + width {
                self.content[i].reset();
            }
            index += width;
            x_offset += width;
        }
        (x_offset as u16, y)
    }
```

I suspect that changing `if width > max_offset.saturating_sub(x_offset)` to `if width >= max_offset.saturating_sub(x_offset)` (gt-or-eq vs. gt) will fix this issue, but I haven't tried it. A cursory reading of the code maps this check to a generic `i > n` which should be either `i >= n` or (equivalently) `!(i < n)`, except transformed a bit to avoid overflow bugs. I think.

I found this while property-testing my app. I continue to be amazed at the ability of property testing to not only find bugs, but to find bugs I'm not even looking for. Also, thanks for writing tui—I've been consistently pleased with it.

**Comment by fdehau** [comment]
I am happy that you enjoyed working with this crate so far and thanks for reporting this bug with all those details. I might have a fix here: #285. Let me know what you think.
