### ISSUE TITLE
Layout::split may cause a panic if used outside of Terminal::draw

### ISSUE THREAD

**Issue by Xandaros** [fdehau/tui-rs#343]
**Describe the bug**
`Layout::split` appears to yield an incorrect result if used outside of the closure given to `Terminal::draw`, which may result in a panic if that result is then used to draw a widget.

At least I think that's what happens, I'm not entirely sure, see below.

**To Reproduce**
An example of this happening can be found at the end of this report. Running the program and then resizing the window in XMonad or i3 with the window in floating mode causes it to panic. Other window managers were not tested - it appears to be fine if the window is in tiling mode, however.

Moving the `layout.split` call in line 27 into the closure two lines below, prevents the panic from happening.
For some reason, replacing `chunks[0]` with `size` also causes this panic if the split call is outside the closure. It works fine if the call is within or isn't made at all.

**Expected behavior**
No panic. Or at least this caveat being documented.

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal Emulator: urxvt
 - Font: Dina
 - Crate version: 0.10
 - Backend: termion

**Additional context**
```rust
use std::io;
use std::sync::{
    mpsc::{channel, Sender},
};
use tui::Terminal;
use tui::backend::TermionBackend;
use tui::layout::Constraint;
use tui::layout::{Direction, Layout};
use tui::text::{Text};
use tui::widgets::{Paragraph};
use termion::input::TermRead;
use termion::screen::AlternateScreen;
use termion::raw::{IntoRawMode, RawTerminal};

type MyBackend = TermionBackend<AlternateScreen<RawTerminal<io::Stdout>>>;

fn draw(terminal: &mut Terminal<MyBackend>) -> Result<(), io::Error> {
    let size = terminal.size()?;
    let layout = Layout::default()
        .direction(Direction::Vertical)
        .constraints(
            [
                Constraint::Min(1),
            ]
            .as_ref()
        );
    let chunks = layout.split(size);  // <--------------------------------------------
    
    terminal.draw(|f| {
        let paragraph = Paragraph::new(Text::from("test"));
        f.render_widget(paragraph, size);
    })?;
    Ok(())
}

enum Event {
    Resize,
    Input(termion::event::Event),
}

fn resize_listener(sender: Sender<Event>) {
    let signals = signal_hook::iterator::Signals::new(&[signal_hook::SIGWINCH]).unwrap();
    std::thread::spawn(move || {
        for _ in signals.forever() {
            sender.send(Event::Resize).unwrap();
        }
    });
}

fn input_listener(sender: Sender<Event>) {
    std::thread::spawn(move || {
        for event in io::stdin().events() {
            if let Ok(event) = event {
                sender.send(Event::Input(event)).unwrap();
            }
        }
    });
}

fn main() -> Result<(), io::Error> {
    let stdout = AlternateScreen::from(io::stdout().into_raw_mode()?);
    let backend = TermionBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;
    terminal.clear()?;
    terminal.hide_cursor()?;
    
    draw(&mut terminal)?;

    let (sender, receiver) = channel::<Event>();

    resize_listener(sender.clone());
    input_listener(sender);


    for event in receiver {
        match event {
            Event::Resize => draw(&mut terminal)?,
            Event::Input(event) => {
                use termion::event::Event;
                use termion::event::Key;
                match event {
                    Event::Key(Key::Char('q')) => break,
                    _ => (),
                }
            }
        }
    }

    Ok(())
}
```

**Comment by fdehau** [comment]
I cannot reproduce the issue. Could you provide a full backtrace of the panic (code compiled in debug mode + `RUST_BACKTRACE=full`) ?

**Comment by Xandaros** [comment]
Sure thing:
```
warning: unused variable: `chunks`
  --> src/main.rs:27:9
   |
27 |     let chunks = layout.split(size);  // <--------------------------------------------
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_chunks`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/tuitest`
thread 'main' panicked at 'Trying to access position outside the buffer: x=203, y=0, area=Rect { x: 0, y: 0, width: 203, height: 62 }', /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:208:9
stack backtrace:
   0:     0x55e3db4a9375 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55e3db4a9375 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55e3db4a9375 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55e3db4a9375 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55e3db4c79cc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55e3db4a7332 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x55e3db4ab9d0 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55e3db4ab9d0 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55e3db4ab9d0 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x55e3db4ab71c - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x55e3db4ac013 - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:526
  11:     0x55e3db4abc0b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x55e3db4abb7b - std::panicking::begin_panic_fmt::h0ed87aa3b2c392e6
                               at src/libstd/panicking.rs:391
  13:     0x55e3db43631d - tui::buffer::Buffer::index_of::hdca9baf0e4825623
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:208
  14:     0x55e3db435fd4 - tui::buffer::Buffer::get_mut::h3718eafd02f30501
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:175
  15:     0x55e3db436e18 - tui::buffer::Buffer::set_style::hcf64d6438c4640fc
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:349
  16:     0x55e3db440974 - <tui::widgets::paragraph::Paragraph as tui::widgets::Widget>::render::hd27864241fb70b69
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/widgets/paragraph.rs:137
  17:     0x55e3db3c515e - tui::terminal::Frame<B>::render_widget::hdf31a6d9fbe1652f
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/terminal.rs:71
  18:     0x55e3db3dc6dd - tuitest::draw::{{closure}}::ha854661285988e98
                               at src/main.rs:31
  19:     0x55e3db3c5a70 - tui::terminal::Terminal<B>::draw::hb9db10ae2552a7ee
                               at /home/xandaros/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/terminal.rs:210
  20:     0x55e3db3c943a - tuitest::draw::h8b92d3a1acff5505
                               at src/main.rs:29
  21:     0x55e3db3c9f40 - tuitest::main::h86e7cbc3af37d66d
                               at src/main.rs:77
  22:     0x55e3db3ec64d - std::rt::lang_start::{{closure}}::h2ff2c9e4bd5fa9e6
                               at /home/xandaros/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23:     0x55e3db4ac3e3 - std::rt::lang_start_internal::{{closure}}::h7cea099ad4edf1eb
                               at src/libstd/rt.rs:52
  24:     0x55e3db4ac3e3 - std::panicking::try::do_call::h42d93372c44025d2
                               at src/libstd/panicking.rs:348
  25:     0x55e3db4ac3e3 - std::panicking::try::hb47a4182362d3341
                               at src/libstd/panicking.rs:325
  26:     0x55e3db4ac3e3 - std::panic::catch_unwind::h2afcfbf3125915b4
                               at src/libstd/panic.rs:394
  27:     0x55e3db4ac3e3 - std::rt::lang_start_internal::h4f696727fe904f48
                               at src/libstd/rt.rs:51
  28:     0x55e3db3ec617 - std::rt::lang_start::h0c396aa1b4054c75
                               at /home/xandaros/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  29:     0x55e3db3ca20a - main
  30:     0x7f71c9a1b002 - __libc_start_main
  31:     0x55e3db3c416e - _start
  32:                0x0 - <unknown>
```

Also, I just did some additional testing and it appears like the panic does not occur in alacritty, but does occur in urxvt.
I suspect the speed of the terminal has something to do with it - especially since it doesn't always happen instantly.
(Also note that I use the mouse to resize the window. This is probably important as it causes lots of resize events. The probability of a panic for each resize event seems to be fairly low)

**Comment by fdehau** [comment]
Ok the issue has nothing to do with `Layout::split` but with the fact that you query the terminal size outside of the draw closure. We query the size before the closure is executed and use it to resize the internal buffers. In your case, the terminal size is reduced between your call to `Terminal::size` and the call to render_widget and you end up accessing an index outside the bounds of the current draw buffer. I would encourage you to query the size from within the closure for reasons described [here](https://github.com/fdehau/tui-rs/blob/ecb482f2978bfbfe396fa29968a4b72e01432c86/src/terminal.rs#L255).

**Comment by Xandaros** [comment]
This should probably be described in the documentation, I don't remember seeing anything regarding that (though I haven't checked again)
Maybe even make the terminal size only available in the draw closure? If the size is only valid inside the closure, you probably shouldn't be able to query it outside in the first place.
